version: 2
jobs:
    dockerbuild:
        machine: true
        steps:
            - checkout
            - run: |
                docker build -t nginx-test:$CIRCLE_SHA1 .
                echo "[default]
                aws_access_key_id = $aws_access_key_id
                aws_secret_access_key = $aws_secret_access_key
                aws_session_token = $aws_session_token
                " > ~/.aws/credentials
                aws s3 ls
    
                

workflows:
    version: 2
    build-workflow:
        jobs:
            - dockerbuild:
                filters:
                    branches:
                        only: master
                context: aws_credentials