version: 2
jobs:
    dockerbuild:
        machine: true
        steps:
            - checkout
            - run: |
                docker build -t nginx-test:$CIRCLE_SHA1 .
                docker images
                

workflows:
    version: 2
    build-workflow:
        jobs:
            - dockerbuild:
                filters:
                    branches:
                        only: master