version: 2
jobs:
    dockerbuild:
        machine: true
        steps:
            - run: |
                docker build  .

workflows:
    version: 2
    build-workflow:
        jobs:
            - dockerbuild:
                filters:
                    branches:
                        only: master